export const resourcesCardList = {
    Burner: ["ACM Linera Burner", "ADZ235 Burner", "ADZ350 Burner", "AVP150 Burner", "AVP300 Burner", "AWZ350 Burner"],
    "Electronic Controls": [
      "AC20 Actuator",
      "ACU460&ACU480 Flame Controller",
      "AFD258 Flame Controller",
      "AFS244 Combustion Controller",
      "AFS258 Combustion Controller",
      "AFW15 Flame Detector",
      "AIC06 Flame Detector",
      "AIC09 Flame Detector",
      "AIC10 Flame Detector",
      "AIC11 Flame Detector",
      "AMF01 Mutichannel Flame Detector",
      "AT-08 Ignition Transformer",
      "AT31 Electric Actuator",
      "AT50 Electric Actuator",
      "AVS1 Ultraviolet Probe",
      "AVS2 Ultraviolet Probe",
      "AVS8 Ultraviolet Probe",
    ],
    "Industrial burners": [
      "A-BF Series Glow Flame",
      "A-D-MC Burner",
      "A-DG Dual Fuel Burner",
      "A-EGR-HMF",
      "A-GCWR Radiant Tube Burner",
      "A-HMF Series High Momentum And Low Nitrogen Burner",
      "A-HTC Ultra-High Temperature Tunnel Kiln Burner",
      "A-IFGR Reflux Low Nitrogen Burner",
      "A-KB Serise Flame Burner",
      "A-MAX Series Self-preheating Burner",
      "A-MO Series Oxygen-enriched Burner",
      "A-PRO Self-Preating Burner",
      "A-RC Integrated Regenerative Burner",
      "A-SHE Effcient Self-Preheating Burner",
      "A-STOR regenerative Burnerpdf",
      "A-U Radiation Tube Burner Series",
      "A-UTO Automatic Adjusting Burner",
      "ACA Aeries Burner",
      "AIC AICA Aeries Burner",
      "AIO AIOA Aeries Burner",
      "AM Venturi Mixer",
      "AMI Ignition Burner",
      "ANX-C H Ultra-Hight Speed Burner",
      "ANX-C M Burner",
      "ASD Integral Burner",
      "ASF Double Orifice Plate Burner",
      "ASR Split Burner",
      "AST Integral Burner",
      "AST-40 Ignition Burner",
      "ATJ Burner",
    ],
    Valves: [
      "A-FON Air Artery Flush Valve",
      "A-FOR Four-Way Reversing Valve",
      "ACK Air Pulse Solenoid Valve",
      "ACO Large Diameter Gas Regulating Valve",
      "ADJ Stabilizing Valve",
      "AF Filter",
      "AFC Linear Valve",
      "AFX Flange Linear Valve",
      "AGH Gas Regulating Valve",
      "AGK Air-Fuel Proportional Valve",
      "AGV Pressure Reducing Valve",
      "AIK Fuel-Air Proportional Valve",
      "AKL Gas_Cold Air Butterfly Valve",
      "AKR Hot Air Butterfly Valve",
      "AKRZ-AKRJAKL Hot Air Butterfly Valve",
      "ALM Manual Air Valve",
      "ALS Manual Hot AIR Valve",
      "AMR Gas Solenoid Valve",
      "AMS Release Valve",
      "ASH Gas Fine Regulating Valve",
      "AVC Air Solenoid Valve",
      "AVE.N-L Gas Solenoid Valve",
      "AVH Hot Air Butterfly Valve",
      "AVM Threaded Cast Iron Air Valve",
      "AZC.N-L Series Gas Combination Solenoid Valve",
      "By-Pass Valve",
    ],
  };
  